# Generated by Django 5.0.2 on 2024-02-24 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kafeel',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tawassut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('admission_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('Activate', 'Activate'), ('Deactivate', 'Deactivate'), ('Dropped Out', 'Dropped Out'), ('Course Complete', 'Course Complete')], max_length=20)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kifalat.class')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kifalat.course')),
                ('kafeel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kifalat.kafeel')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kifalat.section')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=255)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('study_report', models.TextField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('kafeel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kifalat.kafeel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kifalat.student')),
            ],
        ),
        migrations.AddField(
            model_name='kafeel',
            name='tawassut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kifalat.tawassut'),
        ),
    ]
