# Generated by Django 5.0.2 on 2024-02-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_name',
            new_name='class_field',
        ),
        migrations.AddField(
            model_name='student',
            name='sponsoring_since',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive'), ('Dropped Out', 'Dropped Out'), ('Course Complete', 'Course Complete')], max_length=20),
        ),
    ]
