# Generated by Django 5.0.2 on 2024-02-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0003_rename_submission_date_progress_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='receipt_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
