# Generated by Django 5.0.2 on 2024-02-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0004_alter_progress_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
