# Generated by Django 5.0.2 on 2024-02-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifalat', '0005_student_total_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='paid_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
